### ISSUE TITLE
Bug fix: List hidden/unlisted section/s

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#27]
There seem to be a bug in all scanners that for some reason doesn't map a section or some sections.
This video shows a game with a good example of it:
https://youtu.be/2VqcX5AAy-8

**Comment by JeymyAV** [comment]
This can be resolved implementing the new feature Custom Sections:
[https://github.com/avan06/PS4CheaterNeo/issues/28](https://github.com/avan06/PS4CheaterNeo/issues/28)

**Comment by Pharaoh2k** [comment]
> This can be resolved implementing the new feature Custom Sections: #28

Right, while this can indeed be one approach to this issue, it does require prior knowledge from the user/modder about the missing/hidden section/s and some intervention.
Hopefully, avan can find a different approach that can auto-detect and map such section/s without the need for prior knowledge about it and without the need for the user's intervention, as in most cases modders are not even aware that the important section they want and need to scan is "hidden" unless they debug the code, as you did your video.
I don't know if such an automatic detection is at all possible without modifying ps4debug.bin, but hopefully it is.

**Comment by JeymyAV** [comment]
you did in your video. I don't know if such an automatic detection is at all possible without modifying ps4debug.bin, but hopefully it is.

NO!
It is not possible by program like PS4CheaterNeo detect these hidden sections because this a exclusive job by ps4debug or other similar payloads. 
Only theses payloads could be modified to be able to detect it, but is almost impossible because probably the anti-cheat measure is based into corrupt the map memory pointers a there are many ways to do that...

So, the most practical solution is the manual workaround and yes, this required to have or find where are these hidden sections in each game that used it, but is not too much difficult to find out.

**Comment by avan06** [comment]
Are hidden sections always located after 1000000000, as shown in the video example, or can they also appear before, for example, in the gap between section1 and section2 where there are undefined blank addresses?

**Comment by JeymyAV** [comment]
No, the hidden sections can be in anywhere of PS4 memory address, even below 0x400000 but I don't think that any devep could use that address below  0x400000 because is to risky cause the ps4 could crash any time when the system create new dynamic sections/memory.
So the develop could create hidden sections between others sections or the most safe option that is to create at last section assigned to the game, but is impossible to know on each game that use this technique what option they decide to choose and know exactly the range address used without a deep analysis.

That is why the only solution I can think is totally manual, it means to debug each game that use this technique (lucky us there are only a  few), find out how the game use his address memory and to find where the hidden section begins and ends.

**Comment by avan06** [comment]
Thank you JeymyAV for the detailed explanation. I later checked the source code of earlier versions of the ps4debug program. In fact, it also directly requests virtual memory information from the system [`sys_proc_cmd(mp->pid, SYS_PROC_VM_MAP, &args)`]. It seems that even ps4debug itself cannot easily find all hidden sections...

**Comment by Pharaoh2k** [comment]
[**@avan06**](https://github.com/avan06) commented on [Sep 11, 2023, 4:05 PM GMT+7](https://github.com/avan06/PS4CheaterNeo/issues/27#issuecomment-1713475335 "2023-09-11T09:05:13Z - Replied by Github Reply Comments"):
> Thank you JeymyAV for the detailed explanation. I later checked the source code of earlier versions of the ps4debug program. In fact, it also directly requests virtual memory information from the system [`sys_proc_cmd(mp->pid, SYS_PROC_VM_MAP, &args)`]. It seems that even ps4debug itself cannot easily find all hidden sections...
> 
> _Originally posted by @avan06 in https://github.com/avan06/PS4CheaterNeo/issues/27#issuecomment-1713475335_

I think this is correct. I spoke with another dev about this issue and he did say that this is best addressed in ps4debug, so if any dev is able to make a C patch directly for ps4debug, submit to Ctn and have it merged and released as a new ps4debug build, this will be ideal.
If that payload fix option is not possible, then sadly the only solution will be up to each software/dev to workaround.

**Comment by JeymyAV** [comment]
There is no easy way to fix it in any currently payload because all them use the same request to the virtual memory information from the system, and is impossible to know if the response given by the system is the real virtual memory map or if the game has patched/corrupted  this to have invisible sections where hide his stuff.

**Comment by Pharaoh2k** [comment]
I know a few devs that every other dev told them that what they want to do is impossible, but they still found a way, so let's hope that others can find a better way. ;)
If not, your workaround is still available if nothing better can be done of course.

**Comment by avan06** [comment]
I have implemented a mechanism for automatically detecting hidden sections in version [0.9.9.7-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.7-beta). It will automatically check whether there is continuity between the known sections, and if there are undefined memory addresses in between, it will automatically add a new section. The size of the last section will be determined by the "LastHiddenSectionLengthHex" option. I'm not sure if this meets your requirements. Thank you.

**Comment by Pharaoh2k** [comment]
Interesting. So this mechanism can detect both hidden sections between mapped sections and hidden sections above/higher than all the mapped sections?

**Comment by avan06** [comment]
This detection mechanism cannot determine the complete section range, so it requires the user to decide the length of the last section. Currently, the default length is set to 0x40000000. It's not certain how this default length will affect different games or whether it might exceed the game's usable memory range. Therefore, users can customize this option to their preference.

**Comment by Pharaoh2k** [comment]
I like what you did.
In @JeymyAV video, we can see that the last mapped section ends at 0xFE0380000 and the hidden/invisible section starts at 0x1000000000
`0x1000000000-0xFE0380000 = 0x1fc80000`

This means that to reach **the beginning** of 0x1000000000 we just need to add 0x1fc80000.
You added 0x40000000 which should be more than sufficient to cover that entire memory/section and it's customizable as well, so can be adjusted if needed.
Now it's very easy to find out if that high area in memory indeed has any data by simply scanning it for 1 byte bigger than 00.
If the scan comes back with no results, we know that there actually is no hidden section there. We (users) can apply the same test method on all "hidden" sections obviously.

Thank you, avan! :)

**Comment by avan06** [comment]
There's actually a trap here. The maximum length of each section is `Int32 (2147483647 = 7FFFFFFF)`, so the upper limit that `LastHiddenSectionLengthHex` can accept is only `7FFFFFFF`. Although it should be sufficient.

**Comment by Pharaoh2k** [comment]
Ohh, that's one piece of very important info.
So the default size is 0x40000000  and can be increased up to 0x7FFFFFFF, but not over.
Indeed that should be sufficient, but just in case it isn't and users want to try going/scanning even higher, would it be possible to auto-add more sections?
eg. 
if value > 0x7FFFFFFF add/map 1 more "hidden" section
if value > 0x7FFFFFFF x 2 (0xFFFFFFFE) add/map 2 more "hidden" sections
etc.

**Comment by avan06** [comment]
In version [0.9.9.8-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.8-beta), the LastHiddenSectionLengthHex option has been changed from int to ulong type, removing the limitations of int32. It will also automatically segment the sections into fixed sizes, following the standard section segmentation method. thank you.

**Comment by Pharaoh2k** [comment]
That's a very smart way to implement it. :)
Thanks, avan.
Closing.
